# Generated by Django 2.2.23 on 2021-06-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapp', '0002_datesum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateSum',
        ),
    ]
